"""initial schema

Revision ID: 1b1fd944fb20
Revises: 
Create Date: 2026-10-02 14:28:17.403605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1fd944fb20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('deadline_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_next', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=True),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('home_difficulty', sa.Integer(), nullable=False),
    sa.Column('away_difficulty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_gameweek'), 'fixtures', ['gameweek'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('web_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('ownership_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_gameweek_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=False),
    sa.Column('was_home', sa.Boolean(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('expected_goals', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expected_assists', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('selected', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'fixture_id')
    )
    op.create_index('ix_pgs_gameweek', 'player_gameweek_stats', ['gameweek'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pgs_gameweek', table_name='player_gameweek_stats')
    op.drop_table('player_gameweek_stats')
    op.drop_table('players')
    op.drop_index(op.f('ix_fixtures_gameweek'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_table('teams')
    op.drop_table('gameweeks')
    # ### end Alembic commands ###
