"""player chance_of_playing and news

Revision ID: 896e6f5f7567
Revises: e5555c11f254
Create Date: 2026-10-06 14:00:19.491850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896e6f5f7567'
down_revision: Union[str, Sequence[str], None] = 'e5555c11f254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('chance_of_playing', sa.Integer(), nullable=True))
    # server_default fills the column for players already in the table.
    op.add_column('players', sa.Column('news', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'news')
    op.drop_column('players', 'chance_of_playing')
    # ### end Alembic commands ###
