"""gameweek ranked_count

Revision ID: e5555c11f254
Revises: 1b1fd944fb20
Create Date: 2026-10-06 13:54:35.314046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5555c11f254'
down_revision: Union[str, Sequence[str], None] = '1b1fd944fb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameweeks', sa.Column('ranked_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameweeks', 'ranked_count')
    # ### end Alembic commands ###
